name: CI/CD Pipeline

on:
  push:
    paths:
      - '**.py'
      - 'src/**'
      - 'tests/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install black pytest

    - name: Check code style with black
      run: |
        black --check .

    - name: Run tests
      run: |
        pytest

    - name: Push changes (если тесты и black прошли)
      if: success()  
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "CI: Auto-format and test-passed push" || echo "No changes to commit"
        git push origin master
